import { useState } from "react";
import { ArrowLeft, ArrowRight, CheckCircle2 } from "lucide-react";
import { useLocalStorage } from "../../hooks/use-local-storage";
import { PROJECTS_STORAGE_KEY, ACTIVE_PROJECT_STORAGE_KEY, type ProductType, type QAProject } from "../project-workspace/types";

const productOptions: {id:ProductType; label:string; hint:string}[] = [
  {id:"web",label:"Web",hint:"Страницы, формы и браузеры"},{id:"api",label:"API",hint:"Запросы, ответы и контракты"},
  {id:"mobile",label:"Mobile",hint:"Android/iOS и реальные устройства"},{id:"desktop",label:"Desktop",hint:"Windows/macOS/Linux"},
];
export function BeginnerWizard() {
  const [projects,setProjects]=useLocalStorage<QAProject[]>(PROJECTS_STORAGE_KEY,[]); const [,setActiveId]=useLocalStorage(ACTIVE_PROJECT_STORAGE_KEY,"");
  const [step,setStep]=useState(0); const [name,setName]=useState(""); const [type,setType]=useState<ProductType>("web"); const [goal,setGoal]=useState(""); const [risks,setRisks]=useState<string[]>([]); const [done,setDone]=useState(false);
  const suggestions:Record<ProductType,string[]>={web:["Пользователь не может выполнить основной сценарий","Ошибки валидации формы","Некорректная работа в браузерах"],api:["Нарушен контракт API","Ошибки авторизации","Повторный запрос создаёт дубликат"],mobile:["Потеря данных при прерывании","Сбой на части устройств","Проблемы при слабой сети"],desktop:["Ошибка установки/обновления","Потеря локальных данных","Несовместимость с ОС"]};
  const finish=()=>{const project:QAProject={id:crypto.randomUUID(),name:name.trim()||"Мой первый QA-проект",description:goal.trim(),productType:type,environment:"Staging",risks,createdAt:new Date().toISOString()};setProjects([...projects,project]);setActiveId(project.id);setDone(true)};
  if(done)return <div className="mx-auto max-w-xl rounded-xl border border-emerald-500/30 bg-card p-6 text-center"><CheckCircle2 className="mx-auto h-10 w-10 text-emerald-500"/><h2 className="mt-3 text-xl font-semibold">Проект готов</h2><p className="mt-2 text-sm text-muted-foreground">Дальше: уточните требования → выберите техники тест-дизайна → создайте чек-лист → проведите прогон → оформите дефекты и отчёт.</p><button onClick={()=>{setDone(false);setStep(0)}} className="mt-4 rounded-lg border border-border px-3 py-2 text-sm">Создать ещё один</button></div>;
  return <div className="mx-auto max-w-2xl space-y-4"><div><h2 className="text-xl font-semibold">🧭 Мастер для новичка</h2><p className="text-sm text-muted-foreground">Создайте рабочий контекст без AI и платных сервисов.</p></div><div className="flex gap-1">{[0,1,2,3].map(i=><div key={i} className={`h-1.5 flex-1 rounded ${i<=step?"bg-primary":"bg-muted"}`}/>)}</div><section className="rounded-xl border border-border bg-card p-5">
  {step===0&&<div className="space-y-3"><h3 className="font-semibold">1. Что вы тестируете?</h3><input autoFocus value={name} onChange={e=>setName(e.target.value)} placeholder="Например: интернет-магазин" className="w-full rounded-lg border border-border bg-input-background px-3 py-2 text-sm"/><textarea value={goal} onChange={e=>setGoal(e.target.value)} placeholder="Главная цель пользователя и продукта" rows={3} className="w-full rounded-lg border border-border bg-input-background px-3 py-2 text-sm"/></div>}
  {step===1&&<div><h3 className="mb-3 font-semibold">2. Выберите тип продукта</h3><div className="grid grid-cols-2 gap-2">{productOptions.map(option=><button key={option.id} onClick={()=>setType(option.id)} className={`rounded-lg border p-3 text-left ${type===option.id?"border-primary bg-primary/10":"border-border"}`}><b className="text-sm">{option.label}</b><span className="block text-xs text-muted-foreground">{option.hint}</span></button>)}</div></div>}
  {step===2&&<div><h3 className="font-semibold">3. Какие риски важны?</h3><p className="mb-3 text-xs text-muted-foreground">Выберите несколько — они определят приоритет проверок.</p><div className="space-y-2">{suggestions[type].map(risk=><label key={risk} className="flex gap-2 rounded-lg border border-border p-3 text-sm"><input type="checkbox" checked={risks.includes(risk)} onChange={()=>setRisks(risks.includes(risk)?risks.filter(r=>r!==risk):[...risks,risk])}/>{risk}</label>)}</div></div>}
  {step===3&&<div className="space-y-3"><h3 className="font-semibold">4. План первых действий</h3>{["Проверить требования и критерии приёмки","Составить карту рисков","Применить EP/BVA и таблицы решений","Создать чек-лист позитивных и негативных сценариев","Выполнить проверки и зафиксировать доказательства","Оформить дефекты и релизный отчёт"].map((x,i)=><div key={x} className="flex gap-2 text-sm"><span className="text-primary">{i+1}.</span>{x}</div>)}</div>}
  <div className="mt-5 flex justify-between"><button disabled={step===0} onClick={()=>setStep(step-1)} className="flex items-center gap-1 rounded-lg border border-border px-3 py-2 text-sm disabled:opacity-30"><ArrowLeft className="h-4 w-4"/>Назад</button>{step<3?<button onClick={()=>setStep(step+1)} className="flex items-center gap-1 rounded-lg bg-primary px-3 py-2 text-sm text-primary-foreground">Далее<ArrowRight className="h-4 w-4"/></button>:<button onClick={finish} className="rounded-lg bg-primary px-3 py-2 text-sm text-primary-foreground">Создать проект</button>}</div>
  </section></div>;
}
